accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "Unicode-3.0"
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
no-clearly-defined = true

private = { ignore = true }
